name: Update High Scores
on:
  push:
    branches:
      - main
jobs:
  update-highscores:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update high scores
        run: |
          # 更新されたJSONファイルをリポジトリにコミット
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add highscores.json
          git commit -m "Update high scores"
          git push
